// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJG2g4YAV0grI7JJwX1OPZpzsri_GvtYY',
    appId: '1:305153665736:web:f930f33a35f4a4783813fd',
    messagingSenderId: '305153665736',
    projectId: 'cueing-app-as',
    authDomain: 'cueing-app-as.firebaseapp.com',
    storageBucket: 'cueing-app-as.firebasestorage.app',
    measurementId: 'G-2WW0FR2JKE',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJG2g4YAV0grI7JJwX1OPZpzsri_GvtYY',
    appId: '1:305153665736:web:c17118f6631ec9723813fd',
    messagingSenderId: '305153665736',
    projectId: 'cueing-app-as',
    authDomain: 'cueing-app-as.firebaseapp.com',
    storageBucket: 'cueing-app-as.firebasestorage.app',
    measurementId: 'G-7RY9T439NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'YOUR_ANDROID_API_KEY',
  appId: '1:305153665736:android:572868401cae1c193813fd',
  messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  projectId: 'cueing-app-as',
  storageBucket: 'cueing-app-as.appspot.com',
  );


}